[package]
name = "rusty-rogue-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
bracket-bevy = {git = "https://github.com/amethyst/bracket-lib", branch = "bevy"}